apps/cms/urls.py
from  django.urls import path
from .import views
app_name = 'cms'
urlpatterns = [
    path("", views.index, name="index")
]

apps/news/urls.py
from django.urls import path
from . import views
app_name = "news"
urlpatterns = [
    path('',views.index,name="index"),
    path('<int:news_id>/',views.news_detail,name="detail"),
]

apps/xiaofanzhuoauth/urls.py
from django.urls import path
from . import views

app_name = "xiaofanzhuoauth"
urlpatterns = [
    path('login/',views.login_view,name="login"),
    path('logout/',views.logout_view,name="logout"),
    path('img_captcha/',views.img_captcha,name="img_captcha"),
    path('register/',views.register_view,name="register")
]

xfz/urls.py
from django.urls import path,include
from apps.news import views
urlpatterns = [
    path('',views.index,name='index'),
    path('news/',include("apps.news.urls")),
    path('cms/',include("apps.cms.urls")),
    path("account/",include("apps.xiaofanzhuoauth.urls")),
]

apps/cms/models.py
from django.db import models

# Create your models here.

apps/news/models.py
from django.db import models

# Create your models here.

apps/xiaofanzhuoauth/models.py
from django.db import models
from django.contrib.auth.models import User,AbstractBaseUser,PermissionsMixin,BaseUserManager
from shortuuidfield import ShortUUIDField
# Create your models here.

class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, telephone, username, password, **kwargs):
        if not telephone:
            raise ValueError('請輸入手機號')
        if not username:
            raise ValueError('請輸入用戶名')
        if not username:
            raise ValueError('請輸入密碼')
        user = self.model(username=username, telephone=telephone, **kwargs)
        user.set_password(password)
        user.save()
        return user

    def create_user(self, telephone, username, password, **kwargs):
        kwargs['is_superuser'] = False
        return self._create_user(telephone, username, password, **kwargs)

    def create_superuser(self, telephone, username, password, **kwargs):
        kwargs['is_superuser'] = True
        kwargs['is_staff'] = True
        return self._create_user(telephone, username, password, **kwargs)






class User(AbstractBaseUser,PermissionsMixin):
    #主鍵不選用自增長的id 防止到了101 之後 沒數據
    #選擇uuid  uuid 太長佔據空間  所有選擇 shortuuid
    uid = ShortUUIDField(primary_key=True)
    telephone = models.CharField(max_length=11,unique=True)
    email = models.EmailField(unique=True,null=True)
    username = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    data_joined = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = 'telephone'
    #雖然下面只有一個username 但是默認會驗證 username telephone password
    REQUIRED_FIELDS = ['username']
    EMAIL_FIELD = 'email'

    objects = UserManager()

    def get_full_name(self):
        return self.username

    def get_short_name(self):
        return self.username

apps/forms.py
class AllForm(object):

    def get_errors(self):
        errors = self.errors.get_json_data()
        new_errors = {}
        for key,message_dicts in errors.items():
            messages = []
            for message in message_dicts:
                messages.append(message['message'])
            new_errors[key] = messages
        return new_errors

apps/xiaofanzhuoauth/forms.py
from django import forms
from .models import User
from django.core.cache import cache
from apps.forms import AllForm


class LoginForm(forms.Form,AllForm):
    telephone = forms.CharField(max_length=11)
    password = forms.CharField(max_length=20,min_length=6,error_messages={"max_length":"密碼最多20位","min_length":"密碼最短6位數"})
    remember = forms.IntegerField(required=False)

class RegisterForm(forms.Form,AllForm):
    telephone = forms.CharField(max_length=11)
    username = forms.CharField(max_length=20)
    password1 = forms.CharField(max_length=20,min_length=6,error_messages={"max_length":"密码最常不能超过20","min_length":"密码最短不能少于6位"})
    password2 = forms.CharField(max_length=20,min_length=6,error_messages={"max_length":"密码最常不能超过20","min_length":"密码最短不能少于6位"})
    img_captcha = forms.CharField(max_length=4,min_length=4)

    def clean(self):
        cleaned_data = super(RegisterForm,self).clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")
        if password1 != password2:
            raise forms.ValidationError("两次密码输入不一致")
        img_captcha = cleaned_data.get("img_captcha")
        cache_img_captcha = cache.get(img_captcha.lower())

        if not cache_img_captcha or cache_img_captcha.lower() != img_captcha.lower():
            raise forms.ValidationError("图形验证码输入错误")
        telephone = cleaned_data.get("telephone")
        exists = User.objects.filter(telephone=telephone).exists()
        if exists:
            raise forms.ValidationError("该手机号已经存在")
        return cleaned_data

apps/cms/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'cms/index.html')

def login(request):
    return render(request, 'cms/login.html')

apps/news/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'news/index.html')
def news_detail(request,news_id):
    return render(request,'news/news_detail.html')

apps/xiaofanzhuoauth/views.py
from django.shortcuts import render,redirect,reverse
from django.views.decorators.http import require_POST
from django.contrib.auth  import authenticate,login,logout
from .forms import LoginForm,RegisterForm
from utils import restful
from .models import User
from django.http import HttpResponse,JsonResponse
from utils.captcha.xfzcaptcha import Captcha
from io import BytesIO
from django.core.cache import cache
# Create your views here.

# {"code":500,"message":"服務器錯誤","data":""}
def index_view(request):
    #user = User.objects.create_user(telephone="13888888888",username="haha",password="123456")
    return HttpResponse("成功")
@require_POST
def login_view(request):
    form = LoginForm(request.POST)
    if form.is_valid():
        telephone = form.cleaned_data.get('telephone')
        password = form.cleaned_data.get('password')
        remember = form.cleaned_data.get('remember')
        print(telephone)
        print(password)
        print(remember)
        user = authenticate(request,username=telephone,password=password)
        if user:
            if user.is_active:
                login(request,user)
                if remember:
                    request.session.set_expiry(None)
                else:
                    request.session.set_expiry(0)
                return restful.success()
            else:
                return restful.unauth(message="您的账号被冻结")
        else:
            return restful.paramerror(message="手机号或者密码错误")

    else:
        errors = form.get_errors()

        return restful.paramerror(message=errors)


def logout_view(request):
    logout(request)
    return redirect(reverse('news:index'))
@require_POST
def register_view(request):
    form = RegisterForm(request.POST)
    if form.is_valid():
        telephone = form.cleaned_data.get('telephone')
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = User.objects.create_user(telephone=telephone,username=username,password=password)
        login(request,user)
        return restful.success()
    else:
        return restful.paramerror(message=form.get_errors())





def img_captcha(request):
    #第一步 实例化对象 调用
    text,image = Captcha.gene_code()
    #因为 图片不能直接放到  HttpResponse 直接返回

    out = BytesIO() #可以先放到管道中 BytesIO相当于一个管道 存放图片流数据
    image.save(out,'png')#调用image save方法 将图片流数据保存在BytesIO中 指定图片为png


    out.seek(0) #将指针回0
    response = HttpResponse(content_type="image/png") #指定返回内容的类型
    response.write(out.read()) #从管道中读取数据  放到 HttpResponse中
    #这个地方如果 管道指针 不回  0 它会从最后的位置开始往后读  会反回空
    #所以上一步将指针回0
    response['Content-length'] = out.tell() #也就是返回指针的位置

    cache.set(text.lower(),text.lower(),300) #把图形验证码放到缓存中
    return response

front/templates/base/front_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% block header %}

    {% endblock %}
    <meta name="csrf-token" content="{{ csrf_token }}">
    <link rel="stylesheet" href="//at.alicdn.com/t/font_681895_q7ptjm0r8n.css">
    <link rel="stylesheet" href="{% static "css/common/auth.min.css" %}">
    <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static "js/auth.min.js" %}"></script>
    <script src="{% static "js/xfzajax.min.js" %}"></script>

</head>
<body>
    <header class="header">
        <div class="container">
            <div class="logo-box">
                <a href="#"></a>
            </div>
            <ul class="nav">
                <li class="active"><a href="/">创业咨询</a></li>
                <li ><a href="#">创业课堂</a></li>
                <li ><a href="#">付费资讯</a></li>
                <li ><a href="#">搜索</a></li>
            </ul>
            <div class="auth-box">
                <i class="icon-person iconfont signin-btn"></i>
                {% if user.is_authenticated %}
                    <a href="#" class="authenticated-box">{{ user.username }}</a>
                    <a href="{% url "cms:index" %}" class="authenticated-box">管理系统</a>
                    <a href="{% url "xiaofanzhuoauth:logout" %}" class="authenticated-box">退出登录</a>
                {% else %}
                <a href="#" class="signin_btn">登录</a> /
                <a href="#" class="signin_btn">注册</a>
                {% endif %}
            </div>
        </div>
    </header>
    {% block main %}

    {% endblock %}
    <footer class="footer">
        <div class="top-group">
            <div class="top-inner-group">
                <div class="logo-box"></div>
                <div class="detail-group">
                    <div class="line1">
                        <ul class="links">
                            <li><a href="#">关于小饭桌</a></li>
                            <li><a href="#">创业课堂</a></li>
                            <li><a href="#">寻求报道</a></li>
                            <li><a href="#">创业礼包</a></li>
                        </ul>
                        <div class="about-us">
                            <span class="title">关于我们：</span>
                            <ul class="social-group">
                                <li class="weixin">
                                    <div class="wx-qrcode"></div>
                                    <span class="text">xfz008
                                    </span>
                                </li>
                                <li class="weibo">
                                    <a class="text" href="#">小饭桌创业课堂</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="line2">
                        <p class="address">地址：北京市朝阳区东三环北路38号院1号楼17层2001内1、16室</p>
                        <p class="contact">联系方式：400-810-1090（工作日10点-18点）</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="bottom-group">
            ©2017 北京子木投资顾问有限公司 京ICP备15051289号-1
        </div>
    </footer>
    <div class="mask-wrapper">
        <div class="auth-wrapper">
            <div class="close-wrapper">
                <span class="close-btn icon-close iconfont"></span>
            </div>
            <div class="auth-inner-wrapper">
                <div class="scroll-wrapper">
                    <div class="signin-group auth-group">
                        <div class="top-group">
                            <span class="title">请登录</span>
                            <a href="javascript: void(0);" class="switch">立即注册></a>
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                <input type="text" class="form-control" name="telephone" placeholder="请输入手机号码">
                            </div>
                             <div class="input-group">
                                <input type="password" class="form-control" name="password" placeholder="请输入密码">
                            </div>
                            <div class="input-group">
                                <label class="remember-label">
                                    <input type="checkbox" name="remember" value="1">
                                    记住我
                                </label>
                            </div>
                            <div class="input-group">
                                <input type="submit" class="submit-btn logins" value="立即登录">
                            </div>
                        </div>
                    </div>
                    <div class="signup-group auth-group">
                        <div class="top-group">
                            <span class="title">请注册</span>
                            <a href="javascript: void(0);" class="switch">立即登录></a>
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                <input type="text" class="form-control" name="telephone" placeholder="手机号码">
                            </div>
                            <div class="input-group">
                                <input type="text" class="form-control" name="username" placeholder="用户名">
                            </div>
                            <div class="input-group">
                                <div class="short-input-group">
                                    <input type="text" class="form-control" name="img_captcha" placeholder="图形验证码">
                                </div>
                                <div class="input-group-addon">
                                    <img src="{% url 'xiaofanzhuoauth:img_captcha' %}" alt="" class="img_captcha" style="cursor: pointer">
                                </div>
                            </div>
                            <div class="input-group">
                                <input type="text" class="form-control" name="password1" placeholder="密码">
                            </div>
                            <div class="input-group">
                                <input type="text" class="form-control" name="password2" placeholder="确认密码">
                            </div>
                            <div class="input-group">
                                <div class="short-input-group">
                                    <input type="text" class="form-control" name="sms_captcha" placeholder="短信验证码">
                                </div>
                                <div class="input-group-addon">
                                    <span class="sms-captcha-btn">发送验证码</span>
                                </div>
                            </div>
                            <div class="input-group">
                                <input type="submit" class="submit-btn registers" value="立即注册">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

front/templates/cms/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %} | 小饭桌管理系统</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/AdminLTE.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/skins/_all-skins.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css' %}">
    <link rel="stylesheet" href="{% static 'sweetalert/sweetalert.css' %}">
    <script src="{% static 'adminlte/bower_components/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'adminlte/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'adminlte/dist/js/adminlte.min.js' %}"></script>
    <script src="{% static 'sweetalert/sweetalert.min.js' %}"></script>
    <script src="{% static 'js/xfzajax.min.js' %}"></script>
    <script src="{% static 'js/xfzalert.min.js' %}"></script>
    <script src="{% static 'js/message.min.js' %}"></script>
    {% block head %}{% endblock %}
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
    <header class="main-header">
        <!-- Logo -->
        <a href="/" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>CMS</b></span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg">小饭桌后台管理系统</span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>

            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="https://tva4.sinaimg.cn/crop.0.2.636.636.180/88c30c5egw1e7ik7e3k6nj20hs0hswgv.jpg"
                                 class="user-image" alt="User Image">
                            <span class="hidden-xs">高海杰</span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- User image -->
                            <li class="user-header">
                                <img src="https://tva4.sinaimg.cn/crop.0.2.636.636.180/88c30c5egw1e7ik7e3k6nj20hs0hswgv.jpg"
                                     class="img-circle" alt="User Image">
                                <p>
                                    高海杰
                                    <small>Python web开发工程师</small>
                                </p>
                            </li>
                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="#" class="btn btn-default btn-flat">个人中心</a>
                                </div>
                                <div class="pull-right">
                                    <a href="#" class="btn btn-default btn-flat">退出登录</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <form action="#" method="get" class="sidebar-form">
                <div class="input-group">
                    <input type="text" name="q" class="form-control" placeholder="首页">
                    <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
          </span>
                </div>
            </form>
            <!-- /.search form -->
            <!-- sidebar menu: : style can be found in sidebar.less -->
            <ul class="sidebar-menu" data-widget="tree">
                <li class="active">
                    <a href="{% url 'cms:index' %}">
                        <i class="fa fa-home"></i>
                        <span>首页</span>
                    </a>
                </li>
                {% if perms.news.change_news %}
                    <li class="header">新闻管理</li>
                    <li>
                        <a href="{% url 'cms:news_list' %}">
                            <i class="fa fa-list"></i>
                            <span>新闻列表</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'cms:write_news' %}">
                            <i class="fa fa-edit"></i>
                            <span>发布新闻</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'cms:news_category' %}">
                            <i class="fa fa-tag"></i>
                            <span>新闻分类</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'cms:banners' %}">
                            <i class="fa fa-window-restore"></i>
                            <span>轮播图</span>
                        </a>
                    </li>
                {% endif %}
                {% if perms.course.change_course %}
                    <li class="header">课程管理</li>
                    <li>
                        <a href="{% url 'cms:pub_course' %}">
                            <i class="fa fa-tv"></i>
                            <span>发布课程</span>
                        </a>
                    </li>
                {% endif %}
                {% if user.is_superuser %}
                    <li class="header">员工管理</li>
                    <li>
                        <a href="{% url 'cms:staffs' %}">
                            <i class="fa fa-group"></i>
                            <span>员工管理</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </section>
    </aside>
    <div class="content-wrapper">
        <section class="content-header">
            {% block content-header %}{% endblock %}
        </section>
        <section class="content">
            {% block content %}{% endblock %}
        </section>
    </div>
    <footer class="main-footer">
        <strong>小饭桌</strong>后台管理系统
    </footer>
</div>
</body>
</html>

front/templates/cms/index.html
{% extends 'cms/base.html' %}

{% block title %}首页{% endblock %}

{% block content-header %}
    <h1>欢迎来到小饭桌CMS管理系统</h1>
{% endblock %}

front/templates/cms/login.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>扛把子联盟 | 后台管理页面</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{% static 'adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'adminlte/bower_components/font-awesome/css/font-awesome.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static 'adminlte/bower_components/Ionicons/css/ionicons.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'adminlte/dist/css/AdminLTE.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'adminlte/plugins/iCheck/square/blue.css' %}">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="#">扛把子1806</a>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">请登录</p>

    <form action="{% url "xiaofanzhuoauth:login" %}" method="post">
      <div class="form-group has-feedback">
        <input type="text" class="form-control" placeholder="邮箱" name="telephone">
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <input type="password" class="form-control" placeholder="密码" name="password">
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      <div class="row">
        <div class="col-xs-8">
          <div class="checkbox icheck">
            <label>
              <input type="checkbox"> 记住我
            </label>
          </div>
        </div>
        <!-- /.col -->
        <div class="col-xs-4">
          <button type="submit" class="btn btn-primary btn-block btn-flat">登录</button>
        </div>
        <!-- /.col -->
      </div>
    </form>

  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<!-- jQuery 3 -->
<script src="{% static 'adminlte/bower_components/jquery/dist/jquery.min.js' %}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'adminlte/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- iCheck -->
<script src="{% static 'adminlte/plugins/iCheck/icheck.min.js' %}"></script>
<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' /* optional */
    });
  });
</script>
</body>
</html>

front/templates/common/auth.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>授权页面</title>
    <link rel="stylesheet" href="../../dist/css/common/auth.min.css">
    <link rel="stylesheet" href="//at.alicdn.com/t/font_681895_ufv8ns8pw60z4cxr.css">
    <script src="../../dist/js/jquery-3.3.1.min.js"></script>
    <script src="../../dist/js/auth.min.js"></script>

</head>
<body>
    <button id="btn">登录/注册</button>
    <div class="mask-wrapper">
        <div class="auth-wrapper">
            <div class="close-wrapper">
                <span class="close-btn icon-close iconfont"></span>
            </div>
            <div class="auth-inner-wrapper">
                <div class="scroll-wrapper">
                    <div class="signin-group auth-group">
                        <div class="top-group">
                            <span class="title">请登录</span>
                            <a href="javascript: void(0);" class="switch">立即注册></a>
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                <input type="text" class="form-control" name="telephone" placeholder="请输入手机号码">
                            </div>
                             <div class="input-group">
                                <input type="password" class="form-control" name="password" placeholder="请输入密码">
                            </div>
                            <div class="input-group">
                                <label class="remember-label">
                                    <input type="checkbox" name="remember" value="1">
                                    记住我
                                </label>
                            </div>
                            <div class="input-group">
                                <input type="submit" class="submit-btn" value="立即登录">
                            </div>
                        </div>
                    </div>
                    <div class="signup-group auth-group">
                        <div class="top-group">
                            <span class="title">请注册</span>
                            <a href="javascript: void(0);" class="switch">立即登录></a>
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                <input type="text" class="form-control" name="telephone" placeholder="手机号码">
                            </div>
                            <div class="input-group">
                                <input type="text" class="form-control" name="username" placeholder="用户名">
                            </div>
                            <div class="input-group">
                                <div class="short-input-group">
                                    <input type="text" class="form-control" name="img_captcha" placeholder="图形验证码">
                                </div>
                                <div class="input-group-addon">
                                    <img src="" alt="">
                                </div>
                            </div>
                            <div class="input-group">
                                <input type="text" class="form-control" name="password1" placeholder="密码">
                            </div>
                            <div class="input-group">
                                <input type="text" class="form-control" name="password2" placeholder="确认密码">
                            </div>
                            <div class="input-group">
                                <div class="short-input-group">
                                    <input type="text" class="form-control" name="sms_captcha" placeholder="短信验证码">
                                </div>
                                <div class="input-group-addon">
                                    <span class="sms-captcha-btn">发送验证码</span>
                                </div>
                            </div>
                            <div class="input-group">
                                <input type="submit" class="submit-btn" value="立即注册">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>